version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.29.3
    working_directory: ~/app
    steps:
      - checkout
        
      

      
  
      - run:
          name: Install dependencies
          command: flutter pub get

      - run:
          name: Decode Keystore
          command: echo $KEYSTORE_BASE64 | base64 --decode > android/app/my-release-key.jks

      - run:
           name: Create key.properties
           command: |
            cat \<<EOF > android/key.properties
            storeFile=my-release-key.jks
            storePassword=$KEYSTORE_PASSWORD
            keyAlias=$KEY_ALIAS
            keyPassword=$KEY_PASSWORD
            EOF
            

      - run:
          name: Build Signed APK
          command: |
            flutter build apk --release
            mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/myapp-release.apk

      - run:
          name: Build Signed AAB
          command: |
            flutter build appbundle --release
            mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/project-release.aab

      - store_artifacts:
          path: build/app/outputs/flutter-apk/myapp-release.apk
          destination: myapp-release.apk
          

      - store_artifacts:
          path: build/app/outputs/bundle/release/project-release.aab
          destination: project-release.aab

     
      - run:
          name: Upload APK & AAB 
          command: |
            # Upload APK
            RESPONSE_APK=$(curl -s -X POST https://app2.apidoxy.com/api/v1/apps/android/upload-apk \
              -F file=@build/app/outputs/flutter-apk/myapp-release.apk \
              -F shop="cmdodf60l000028vh5otnn9fg" \
              -F version="1.0.0" \
              -F releaseNotes="Initial release" \
              -F upload_preset=unsigned_upload)

            APK_URL=$(echo $RESPONSE_APK | jq -r '.secure_url')
            echo "APK URL: $APK_URL"
            # Optional: Notify server
            # curl -X POST https://yourserver.com/api/build-complete \
            #  -H "Content-Type: application/json" \
            #  -d "{\"apk_url\":\"$APK_URL\", \"aab_url\":\"$AAB_URL\", \"build_id\":\"$CIRCLE_WORKFLOW_ID\"}"

workflows:
  build_and_upload:
    jobs:
      - build
