version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:main
    steps:
      - checkout

      - run:
          name: Flutter Version
          command: flutter --version

      - run:
          name: Get Dependencies
          command: flutter pub get

      - run:
          name: Build APK
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  build_apk:
    jobs:
      - build
