---
  version: 2.1
  jobs: 
    build_apk: 
      docker: 
        - 
          image: "ghcr.io/cirruslabs/flutter:3.29.3"
      resource_class: "large"
      steps: 
        - "checkout"
        - 
          run: 
            name: "Check Flutter Version"
            command: "flutter --version"
        - 
          run: 
            name: "Install dependencies"
            command: "flutter pub get"
        - 
          run: 
            name: "Rename Package Name"
            command: "dart run change_app_package_name:main com.new.package.name"
        - 
          run: 
            name: "Rename App Nickname"
            command: "dart run rename_app:main all='My App Name'"
        - 
          run: 
            name: "Generate Splash Screen"
            command: "dart run flutter_native_splash:create --path=nativeSplash.yaml"
        - 
          run: 
            name: "Generate App Icon"
            command: "dart run flutter_launcher_icons:generate"
        - 
          run: 
            name: "Generate Version Code"
            command: "dart run cider version 2.0.0"
        - 
          run: 
            name: "Build APK"
            command: "flutter build apk --release"
        - 
          store_artifacts: 
            path: "build/app/outputs/flutter-apk/app-release.apk"
            destination: "app-release.apk"
  workflows: 
    build: 
      jobs: 
        - "build_apk"

