version: 2.1

orbs:
  flutter: circleci/flutter@2.0.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout

      - run:
          name: Install Flutter dependencies
          command: flutter pub get

      - run:
          name: Build APK
          command: flutter build apk --release

      - persist_to_workspace:
          root: .
          paths:
            - build/app/outputs/flutter-apk/app-release.apk

workflows:
  build_apk:
    jobs:
      - build
