version: 2.1

jobs:
  build_apk:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.29.3
    resource_class: large
    steps:
      - checkout

      - run:
          name: Check Flutter Version
          command: flutter --version

      - run:
          name: Install dependencies
          command: flutter pub get

      - run:
          name: Build APK
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  build:
    jobs:
      - build_apk
