version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:3.22.1
    steps:
      - checkout

      - run:
          name: Flutter Version
          command: flutter --version

      - run:
          name: Get dependencies
          command: flutter pub get

      - run:
          name: Build release APK
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

      - persist_to_workspace:
          root: .
          paths:
            - build/app/outputs/flutter-apk/app-release.apk

workflows:
  build_apk:
    jobs:
      - build
